#!/usr/bin/env python

# converted and modified from http://errtheblog.com/posts/89-huba-huba

import os
import errno
import stat

home = os.getenv('REALHOME', os.path.expanduser('~'))

dotfiles_dir = os.path.dirname(os.path.abspath(__file__))
os.chdir(dotfiles_dir)

for fname in os.listdir(dotfiles_dir):
    if fname == 'install': continue
    if fname == 'README.md': continue
    if fname == 'LICENSE.txt': continue
    if fname == 'ignored': continue
    if fname.startswith('.'): continue

    target, ext = os.path.splitext(fname)
    if ext != '.zsh':
        target = fname

    target = os.path.join(home, '.{}'.format(target))

    fpath = os.path.abspath(fname)

    try:
        os.symlink(fpath, target)
        print('{} symlink created'.format(target))
    except OSError as e:
        if e.errno == errno.EEXIST:
            pass # I don't care if the file/dir already exists
        else:
            raise e

# git push on commit
post_commit = os.path.join(dotfiles_dir, '.git/hooks/post-commit')
with open(post_commit, mode='w') as f:
    f.write('git push')
os.chmod(post_commit, 0o755)
