#!/usr/bin/env ruby

# modified from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path(ENV['REALHOME'])

dotfiles_dir = File.expand_path(File.dirname(__FILE__))
Dir.chdir(dotfiles_dir)

Dir['*'].each do |file|
  next if file =~ /install/
  next if file =~ /README.md/
  next if file =~ /ignored/

  target = File.join(home, ".#{file}")
  `ln -sn #{File.expand_path file} #{target} > /dev/null 2>&1`
end

# git push on commit
`echo 'git push' > .git/hooks/post-commit`
`chmod 755 .git/hooks/post-commit`
