#!/usr/bin/python

from apiclient.discovery import build

import argparse
import json
import os
import re
from urllib import quote


parser = argparse.ArgumentParser(description='Searches Google for your query '
                                             'and returns the first result')
parser.add_argument('query', nargs='+', help='your search query')
args = parser.parse_args()


def reduceWhitespace(text):
    return re.sub(r'\s+', ' ', text)


def search():
    query = ' '.join(args.query)

    keyPath = os.path.join(os.path.dirname(os.path.realpath(__file__)), 'apikeys.json')
    with open(keyPath) as keyFile:
        j = json.load(keyFile)
        key = j['google']
        cx = j['google-customsearch-id']

    service = build('customsearch', 'v1', developerKey=key)
    res = service.cse().list(
        q=quote(query),
        cx=cx
    ).execute()

    first = res[u'items'][0]
    title = first[u'title']
    snippet = first[u'snippet']
    link = first[u'link']

    title = reduceWhitespace(title)
    snippet = reduceWhitespace(snippet)

    return u'{} | {} | {}'.format(title, snippet, link)


if __name__ == '__main__':
    print(search())
