#!/bin/sh
if type "nvim" &> /dev/null; then
    MYVIMRC=$REALHOME/.vimrc nvim -u $REALHOME/.vimrc "$@"
elif type "vim" &> /dev/null; then
    MYVIMRC=$REALHOME/.vimrc vim -u $REALHOME/.vimrc "$@"
else
    nano
fi

