#!/usr/bin/env zsh

source "$DOTFILES/ignored/env_colors.sh"
info_col=$CYAN
cmd_col=$GREEN

info_msg() {
    echo -e "\n${info_col}$@${COLOR_RESET}"
}

info_eval() {
    echo -e "${info_col}\$ ${cmd_col}$@${COLOR_RESET}"
    eval "$@"
}

update_yay() {
    info_msg "### Updating Packages"
    info_eval yay -Syu &&\
    info_msg "### Cleaning Up Pacman Cache" &&\
    info_eval yay -Sc --noconfirm
}

update_apt() {
    info_msg "### Updating Packages"
    info_eval sudo apt update &&\
    info_eval sudo apt upgrade &&\
    info_msg "### Cleaning Up apt" &&\
    info_eval sudo apt autoremove &&\
    info_eval sudo apt autoclean
}

update_flatpaks() {
    info_msg "### Updating Flatpaks"
    info_eval sudo flatpak update --noninteractive --assumeyes &&\
    info_msg "### Removing Unused Flatpaks" &&\
    info_eval sudo flatpak uninstall --unused
}

update_dotfiles() {
    info_msg "### Updating .dotfiles"

    unsetopt pushd_ignore_dups
    pushd $HOME/.dotfiles > /dev/null 2>&1
    info_eval git pull &&\
    info_eval git submodule update --init --recursive &&\
    info_eval git submodule foreach git checkout master &&\
    info_eval git submodule foreach git pull
    info_eval ./install
    echo ""
    #source "$HOME/.zshenv"
    #source "$HOME/.zshrc"
    popd > /dev/null 2>&1
    setopt pushd_ignore_dups
}

update() {
    if type "yay" > /dev/null 2>&1; then
        update_yay
    fi
    if type "apt" > /dev/null 2>&1; then
        update_apt
    fi
    if type "flatpak" > /dev/null 2>&1; then
        update_flatpaks
    fi
    update_dotfiles
}

update
